CREATE TABLE ADMINISTRATIVO (IDADMINISTRATIVO NUMBER(9) NOT NULL, RUNAD VARCHAR2(10), NOMBRESAD VARCHAR2(40) NOT NULL, APELLIDOSAD VARCHAR2(40) NOT NULL, CORREOE VARCHAR2(50) NOT NULL, AREA VARCHAR2(30) NOT NULL, PRIMARY KEY (IDADMINISTRATIVO));




CREATE TABLE CAPACITACION (IDCAPACITACION NUMBER(9) NOT NULL, CAPFECHA VARCHAR2(20), CAPHORA VARCHAR2(20), CAPLUGAR VARCHAR2(100), CAPDURACION VARCHAR2(20), CLIENTE_RUTCLIENTE VARCHAR2(20), CAPCANTIDAD NUMBER(38), PRIMARY KEY (IDCAPACITACION));



CREATE TABLE CLIENTE (IDCLIENTE NUMBER(9) NOT NULL, RUTCLIENTE VARCHAR2(10), CLINOMBRES VARCHAR2(30) NOT NULL, CLIAPELLIDOS VARCHAR2(50) NOT NULL, CLITELEFONO VARCHAR2(20) NOT NULL, CLIAFP VARCHAR2(30), CLISISTEMASALUD VARCHAR2(10), CLIDIRECCION VARCHAR2(100) NOT NULL, CLICOMUNA VARCHAR2(50) NOT NULL, CLIEDAD NUMBER(3) NOT NULL, PRIMARY KEY (IDCLIENTE));




CREATE TABLE PAGO (IDPAGO NUMBER(3) NOT NULL, FECHAPAGO VARCHAR2(10) NOT NULL, RUT VARCHAR2(10) NOT NULL, NOMBRECLI VARCHAR2(40) NOT NULL, MONTO NUMBER(10), PRIMARY KEY (IDPAGO));




CREATE TABLE PROFESIONAL (IDPROFESIONAL NUMBER(9) NOT NULL, RUNPRO VARCHAR2(10), NOMBRESPRO VARCHAR2(40) NOT NULL, APELLIDOSPRO VARCHAR2(40) NOT NULL, TELEFONO VARCHAR2(20) NOT NULL, TITULOPRO VARCHAR2(30) NOT NULL, PROYECTO VARCHAR2(240) NOT NULL, PRIMARY KEY (IDPROFESIONAL));




CREATE TABLE VISITA (IDVISITA NUMBER(9) NOT NULL, FECHA VARCHAR2(10) NOT NULL, HORA VARCHAR2(5) NOT NULL, LUGAR VARCHAR2(50) NOT NULL, COMENTARIO VARCHAR2(250), RUTCLIENTE VARCHAR2(10) NOT NULL, REALIZADO NUMBER(1) NOT NULL, NOMBRECLI VARCHAR2(20) NOT NULL, PRIMARY KEY (IDVISITA));




